[package]
name = "rankBot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = { version="0.11.5", features = [ "builder",
    "cache",
    "chrono",
    "client",
    "gateway",
    "http",
    "model",
    "utils",
    "rustls_backend"], default-features = false }
rusqlite = { version = "0.28.0", features = ["bundled"] }
env-file-reader = "0.3.0"
tokio = { version = "1.23.0", features = ["full"] }
poise = "0.5.2"
tokio-rusqlite = "0.3.0"
log = "0.4.17"
rsnltk = "0.1.3"
fern = "0.6.1"
chrono = "0.4.23"