//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub snowflake: i64,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub message_count: i32,
    #[sea_orm(column_type = "Float")]
    pub score: f32,
    pub guild: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::guilds::Entity",
        from = "Column::Guild",
        to = "super::guilds::Column::Snowflake",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Guilds,
    #[sea_orm(has_many = "super::messages::Entity")]
    Messages,
}

impl Related<super::guilds::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Guilds.def()
    }
}

impl Related<super::messages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Messages.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
